### ISSUE TITLE
steam卡片突然不能正常显示

### ISSUE THREAD

**Issue by lemonyueya** [yuyinws/steam-card#100]
在steam card配置页面，显示我的账号已经被禁止。在论坛显示错误代码403，问题已出现约1周，中间有尝试使用朋友账号可正常显示，本人账号多次尝试均不行
![image](https://github.com/yuyinws/steam-card/assets/85669033/0f69f9e7-9c3b-4105-b4f4-de3ffb81fa96)
![image](https://github.com/yuyinws/steam-card/assets/85669033/420f0807-21ae-49a1-8b43-1070668042c2)
希望大大帮我看看是什么方面的问题

**Comment by yuyinws** [comment]
前段时间后台显示有个账号(76561198434998728)的流量消耗太大，所以把这个账号屏蔽掉了，应该就是你的。

可以参考[这个文档](https://github.com/yuyinws/steam-card/blob/master/README-CN.md#-%E9%83%A8%E7%BD%B2)尝试自己部署一下。如果自己部署遇到问题可以加我QQ(657508366)
