### ISSUE TITLE
我的steam卡片无法显示了…不知道为什么…

### ISSUE THREAD

**Issue by Itzamana** [yuyinws/steam-card#11]
![](https://steamcard.vercel.app/card/76561197967027400)

https://steamcard.vercel.app/card/76561197967027400

错误提示
Error: Steam接口请求错误

我在论坛看了下其他人的都好着呢，就我的卡片突然这样了…
应该是从今天0点开始的，昨天都正常…

**Comment by Itzamana** [comment]
我没有修改steam社区的任何设置，就只是突然变成这样了…

**Comment by yuyinws** [comment]
@Itzamana 
排查了一下原因，是由于你最近游玩过一个appid为567000的游戏（上steamdb查了一下，叫Tapocalypse）
这个游戏Steam那边的接口没有把封面等信息传过来，导致渲染出错了。
我近期修复一下。

**Comment by Itzamana** [comment]
感谢回复，应该是挂卡的时候挂到这个喜加一了…

**Comment by yuyinws** [comment]
已修复，由于缓存，可能不会立马看到效果，手动清一下浏览器数据即可。
