### ISSUE TITLE
一个小建议…

### ISSUE THREAD

**Issue by Itzamana** [yuyinws/steam-card#19]
看到大佬又更新可选英语啦，然后导致网址后面要加的参数越来越多了，就想到这些参数是不是有更方便的添加方式呢…

现在的情况是填写参数顺序固定，用true和false来控制开关，比如
https://steamcard.vercel.app/card/76561198028121353/dark/false/false/en （暗色，不显示群图标，不显示徽章，英文界面）
https://steamcard.vercel.app/card/76561198028121353/light/true/true/en （亮色，显示群图标，显示徽章，英文界面）

但是我们有默认值呀，如果改成这样：参数不固定顺序，用关键字来控制参数开启，默认值不变的情况下
上面第一个就可以改为 https://steamcard.vercel.app/card/76561198028121353/en
上面第二个就可以改为 https://steamcard.vercel.app/card/76561198028121353/en/badge/light/group

“en”“badge”“light”“group”的顺序可以变，只需检测是否有关键字，这样的话以后如果再添加其他参数就会方便一些……

感谢大佬的签名服务~~

**Comment by yuyinws** [comment]
确实是个问题，使用true和false看起来也不太直观
但是改成你提的这种参数不固定的形式与现有的这套模式很难兼容，会对目前正在使用这个服务的用户造成影响。

受你启发，我想到了一种更方便兼容的模式：
将URL中的第二个参数改成需要传递的关键字,多个关键字之间用逗号隔开，需要使用哪个就添加哪个，不添加则使用默认值
例如：`https://steamcard.vercel.app/card/76561198028121353/en,badge,light,group`

后面我会加上这种方式，在文档中也会优先推荐使用它。

**Comment by Itzamana** [comment]
嗯，大佬这个办法确实更好一些的，赞~
