### ISSUE TITLE
小建议…

### ISSUE THREAD

**Issue by Itzamana** [yuyinws/steam-card#2]
详见论坛
https://keylol.com/forum.php?mod=redirect&goto=findpost&ptid=777417&pid=15905662

**Comment by yuyinws** [comment]
ok 我看看能不能实现

**Comment by Itzamana** [comment]
> ok 我看看能不能实现

感谢回复，我那个示意图半夜随手做的，不是很精细，具体位置估计还得微调一下…

**Comment by yuyinws** [comment]
卡片样式已优化
![img](https://steamcard.vercel.app/card/76561198340841543)

**Comment by Itzamana** [comment]
![](https://steamcard.vercel.app/card/76561197967027400)

大佬真给力，这太好看了~

**Comment by Itzamana** [comment]
> 卡片样式已优化 

大佬…群组数和徽章数位置反了……
