### ISSUE TITLE
错误信息 Error: Error: Request failed with status code 404

### ISSUE THREAD

**Issue by sysuid** [yuyinws/steam-card#24]
![](https://steamcard.vercel.app/card/76561197999668297/dark/true/true)

看了一下之前的issue，可能跟玩过的游戏有关? #11

**Comment by sysuid** [comment]
也有可能跟头像有关，头像和游戏封面都有404

**Comment by yuyinws** [comment]
是头像的原因 重新上传一个头像应该就没问题了
![Snipaste_2022-04-22_09-16-12.jpg](https://s2.loli.net/2022/04/22/2nvJlkXrAMzG4N5.jpg)

**Comment by sysuid** [comment]
> 

有没有办法加个exception？专门找的404头像:)

**Comment by yuyinws** [comment]
已修复#25

另外可以使用`https://steamcard.vercel.app/card/76561197999668297/badge,group`这种更直观简洁的形式引用卡片
![](https://steamcard.vercel.app/card/76561197999668297/badge,group)
