### ISSUE TITLE
部署你自己的应用实例

### ISSUE THREAD

**Issue by yuyinws** [yuyinws/steam-card#38]
随着应用访问量越来越大，原先的`steamcard.vercel.app`实例流量已近上限，可能会经常出现获取steam卡片失败的情况，为了可以稳定访问，大家可以按照下面的方式部署自己的应用实例。

0. 前提条件
 - 1个Github账号
 - 1个[Steam Api Key](https://steamcommunity.com/dev/apikey)

1. 点击下方按钮
[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2Fyuyinws%2Fsteam-card&env=STEAM_KEY&envDescription=YOUR_STEAM_KEY&envLink=https%3A%2F%2Fsteamcommunity.com%2Fdev%2Fapikey)

2. 选择`Continue With Github`

3. 输入Github仓库名称（自定义，只要与现有的不重复就行） 再点击`Create`按钮
![image](https://user-images.githubusercontent.com/38490578/184270136-7a275133-9ba8-4781-9b99-ea4cbf792202.png)

4. 在`STEAM_KEY`一栏输入前面准备的`Steam Api Key` 再点击`Deploy`按钮
![image](https://user-images.githubusercontent.com/38490578/184271594-e45f9042-a8b1-4edc-b2ae-58a2f0a3ff13.png)

5. 应用构建完成后，进入到该应用的`Settings-Domains`页面，可以看到你的应用域名，用该域名替换之前的`steamcard.vercel.app`即可
![image](https://user-images.githubusercontent.com/38490578/184272140-51d72b6c-ddb0-4139-8bd8-3e27b138640b.png)

**Comment by Itzamana** [comment]
![image](https://user-images.githubusercontent.com/20204389/186897841-41641f18-b87a-4108-a49c-282dbb6a6aa2.png)

不管是用steamcard.vercel.app还是自己部署…都会出现这个错误…

**Comment by yuyinws** [comment]
@Itzamana 

可以加我qq（657508366） 帮你看看

**Comment by yuyinws** [comment]
@Itzamana 
原来的服务已恢复，需要把`steamcard.vercel.app` 修改为 `card.yuy1n.io`
