### ISSUE TITLE
More customization

### ISSUE THREAD

**Issue by reincarnationwhen** [yuyinws/steam-card#46]
Can we get a way to change colors? or atleast the background/text color

**Comment by yuyinws** [comment]
Do you mean themes?
<img width="1481" alt="image" src="https://user-images.githubusercontent.com/38490578/190881523-b89dcbaa-fb28-4509-908e-873c71cb0f43.png">

**Comment by reincarnationwhen** [comment]
yeah but a way to change their colors ourselves with a color picker and not a set theme

**Comment by yuyinws** [comment]
Added.
Now you can use custom color by `color hex`.
eg: `https://card.yuy1n.io/card/76561198028121353/text-cc3300,bg-3399ff`

![card](https://card.yuy1n.io/card/76561198028121353/text-cc3300,bg-3399ff)
