### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by upojzsb** [yuyinws/steam-card#61]
The generated [Steam card](https://card.yuy1n.io/card/76561198277143434/dark,en,badge,group,artworks,games,badges) only contains the following statements:

```text
error
TypeError: Cannot read properties of undefined (reading 'length')
```

Maybe because I hid all my information, like games I owned and played records.
In this case, the card may show the avatar and level 0 like [steamid.pro](https://steamid.pro/lookup/76561198277143434) did.

This is a great change to show my avatar, and after the fix, I would definitely add my card to my own blow. : - )

**Comment by yuyinws** [comment]
This bug had been fixed
![card](https://card.yuy1n.io/card/76561198277143434/dark,en,badge,group,artworks,games,badges)

By the way, I recommend you make your Steam information in public status to get richer card content.
