### ISSUE TITLE
部署vercel后出现错误

### ISSUE THREAD

**Issue by govmoe** [yuyinws/steam-card#83]
出现了 FetchError: fetch failed(https://steamcommunity.com/profiles/id)

**Comment by yuyinws** [comment]
尝试一下在项目的设置中把Nodejs版本改成`16.x`然后重新部署
![image](https://user-images.githubusercontent.com/38490578/229757287-ca114ad6-51b7-4875-a41e-1e6525a2d52a.png)

**Comment by govmoe** [comment]
行

**Comment by govmoe** [comment]
问题解决了，谢谢！
